stages:
  - deploy
deploy:
  image: docker:19.03.0
  stage: deploy
  variables:
    DOCKER_HOST: "tcp://meetyourtutor.online:2376"
    DOCKER_CERT_PATH: "certs"
    DOCKER_TLS_VERIFY: "1"
  before_script:
    - mkdir $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker stack deploy --with-registry-auth -c docker-compose.yml traefik